### ISSUE TITLE
Unable to find stub "config/vite.stub"

### ISSUE THREAD

**Issue by Bricklou** [adonisjs/vite#9]
### Package version

3.0.0-8

### Describe the bug

I'm trying to configure vite on my project, but the configure command fail to create the config file:
```
node ace configure @adonisjs/vite
[ error ] Unable to find stub "config/vite.stub"
at StubsManager.build (file:///home/louis/Documents/programmation/projets/hand-drawing-media-pipe/node_modules/.pnpm/@adonisjs+application@8.1.0_@adonisjs+config@5.0.1_@adonisjs+fold@10.0.1/node_modules/@adonisjs/application/build/manager-SLF47P6C.js:278:13)
at async Codemods.makeUsingStub (file:///home/louis/Documents/programmation/projets/hand-drawing-media-pipe/node_modules/.pnpm/@adonisjs+core@6.3.1_@adonisjs+assembler@7.2.3/node_modules/@adonisjs/core/build/modules/ace/codemods.js:226:22)
at async Module.configure (file:///home/louis/Documents/programmation/projets/hand-drawing-media-pipe/node_modules/.pnpm/@adonisjs+vite@3.0.0-8_@adonisjs+core@6.3.1_vite@5.2.6/node_modules/@adonisjs/vite/build/index.js:14:3)
at async Configure.run (file:///home/louis/Documents/programmation/projets/hand-drawing-media-pipe/node_modules/.pnpm/@adonisjs+core@6.3.1_@adonisjs+assembler@7.2.3/node_modules/@adonisjs/core/build/commands/configure.js:114:9)
at async Configure.exec (file:///home/louis/Documents/programmation/projets/hand-drawing-media-pipe/node_modules/.pnpm/@adonisjs+core@6.3.1_@adonisjs+assembler@7.2.3/node_modules/@adonisjs/core/build/modules/ace/commands.js:51:28)
at async #execMain (file:///home/louis/Documents/programmation/projets/hand-drawing-media-pipe/node_modules/.pnpm/@adonisjs+ace@13.0.0/node_modules/@adonisjs/ace/build/index.js:1481:7)
at async AceProcess.handle (file:///home/louis/Documents/programmation/projets/hand-drawing-media-pipe/node_modules/.pnpm/@adonisjs+core@6.3.1_@adonisjs+assembler@7.2.3/node_modules/@adonisjs/core/build/src/ignitor/ace.js:66:9)
```

**Comment by Julien-R44** [comment]
Thanks for the issue

Fixed with the latest release
